[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"


[[redirects]]
  from = "/api/*"
  to = "https://codejeopardy-7116bb4be6a5.herokuapp.com/api/:splat"
  status = 200


[[redirects]]
  from = "*"
  to = "index.html"
  status = 200
