[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"


[[redirects]]
  from = "/*y"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/api/game-categories/"
  to = "https://codejeopardy-7116bb4be6a5.herokuapp.com/api/game-categories"
  status = 200