[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"


[[redirects]]
  from = "/api/*"
  to = "https://codejeopardy-7116bb4be6a5.herokuapp.com/api/"
  status = 200



